# Generated by Django 3.2.17 on 2023-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registercustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('pnumber', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('extraincome', models.CharField(max_length=100)),
                ('appcode', models.CharField(max_length=100)),
                ('amountneeded', models.CharField(max_length=100)),
                ('moneyfor', models.CharField(max_length=100)),
                ('creditscore', models.CharField(max_length=100)),
                ('bankname', models.CharField(max_length=100)),
                ('bankingtime', models.CharField(max_length=100)),
                ('routing', models.CharField(max_length=100)),
                ('accountnumber', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
