# Generated by Django 3.2.17 on 2023-03-28 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casdata', '0002_cardnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnumbers',
            name='dateandtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
